version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_user
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"  
    volumes:
      - ./postgres_data/user_db:/var/lib/postgresql/data  

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_capstone
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
